#!/bin/sh
# Load functions and variables
. /usr/bin/common
export NEWT_COLORS='root=,black border=white,black window=white,black title=white,black textbox=white,black listbox=white,black'

whiptail_height="$(($(tput lines) - 6))"
whiptail_width="$(($(tput cols) - 20))"

while true; do
  CHOICE="$(whiptail --nocancel --title "Odysseyn1x $ODYSSEYN1X_VERSION" --menu '' $whiptail_height $whiptail_width 7 \
    '1' 'Checkra1n' \
    '2' 'Checkra1n (A9X)' \
    '3' 'Odysseyra1n' \
    '4' 'Project Sandcastle' \
    '5' 'SSH' \
    '6' 'Shell' \
    '7' 'Shut down' \
    '8' 'Reboot' 3>&1 1>&2 2>&3)"
  case "$CHOICE" in
    1)
      clear
      /usr/bin/checkra1n
      ;;
    2)
     clear
     /usr/bin/checkra1n -k /opt/PongoConsolidated.bin
     ;;
    3)
      clear
      /usr/bin/odysseyra1n
      ;;
    4)
      /usr/bin/projectsandcastle_menu
      ;;
    5)
      clear
      /usr/bin/ssh_into_ios
      ;;
    6)
      clear
      break
      ;;
    7)
      odysseyn1x_logo
      sleep 2
      /usr/sbin/shutdown now
      ;;
    8)
      /usr/sbin/reboot
      ;;
  esac
done
